---
title: "Práctica 4"
author: "David Charte"
date: "Inteligencia de Negocio - Universidad de Granada"
output: pdf_document
---

```{r setup, include=F}
setwd("~/Documents/IN/p4")
options(java.parameters = "-Xmx16g")
library(RWeka)
library(caret)
```

```{r machine_data}
sysinfo = as.list(Sys.info())
cpuinfo = system(ifelse(sysinfo$sysname == "Darwin",
                        "sysctl -n machdep.cpu.brand_string",
                        "lscpu | grep model"),
                 intern = TRUE)
meminfo = system(ifelse(sysinfo$sysname == "Darwin",
                        "system_profiler SPHardwareDataType | grep Memory",
                        "cat /proc/meminfo | grep MemTotal"),
                 intern = TRUE
                 )
paste(sysinfo$sysname, sysinfo$release, "/", cpuinfo, "/", meminfo)
```

```{r fakeload, include=F}
covertype = "covertype"
kddcup = "kddcup99"
poker = "pokerhand"
protein = "protein"
```

```{r partition, echo=F}
NUM_PARTITIONS = 5
makePartitions = function(name) {
  filename = paste0(name, "_partitions.Rda")
  
  if (file.exists(filename)) {
    load(filename)
    temp = partitions
    rm(partitions)
    return(temp)
  } else {
    current = read.arff(paste0(name, ".arff"))
    inTrain = createDataPartition(current$class, p = 0.8, list = FALSE)
    partitions = list(
      training = current[inTrain,],
      test = current[-inTrain,]
    )
    partitions$training$fold = createFolds(partitions$training$class, k = NUM_PARTITIONS, list = FALSE)
    save(partitions, file = filename)
    return(partitions)
  }
}

getFolds = function(set, folds) { set[set$fold %in% folds, names(set) != "fold"] }

getPredictions = function(set, classifier, control = Weka_control(), stratified = FALSE) {
  prefix = if (stratified) "strat" else "scala"
  # Get partitions
  partitions = makePartitions(set)
  
  # Train classifiers
  filename = paste(prefix, set, gsub("/", "-", classifier), "classifiers.Rda", sep="_")
  cl = if (file.exists(filename)) {
    cat("Loading saved classifiers for", set)
    load(filename)
    temp = classifiers
    rm(classifiers)
    temp
  } else {
    classifiers = lapply(1:NUM_PARTITIONS, function(i) {
      cat(paste0("Starting classifier ", i, "...\n"))
      start = Sys.time()
      model = make_Weka_classifier(classifier)(class ~ .,
                                               data = getFolds(partitions$training, if (stratified) i else 1:i),
                                               control = control)
      end = Sys.time()
      list(model = model, time = end - start)
    })
    
    save(classifiers, file = filename)
    classifiers
  }
  
  # Get predictions
  filename = paste(prefix, set, gsub("/", "-", classifier), "predictions.Rda", sep="_")
  pred = if (file.exists(filename)) {
    cat("Loading existing predictions for", set)
    load(filename)
    temp = predictions
    rm(predictions)
    temp
  } else {
    predictions = lapply(1:NUM_PARTITIONS, function(i) {
      cat(paste0("Predicting with classifier ", i, "...\n"))
      predict(cl[[i]]$model, newdata = partitions$test, type = "probability")
    })
    
    save(predictions, file = filename)
    predictions
  }
  
  lapply(1:NUM_PARTITIONS, function(i) list(model = cl[[i]]$model, time = cl[[i]]$time, predictions = pred[[i]]))
}
```

## Estudio de escalabilidad

```{r scala}
scalabilityTest = function(set, classifier, control = Weka_control()) {
  getPredictions(set, classifier, control, stratified = FALSE)
}
```

```{r scalability}
cov_j48 = scalabilityTest(covertype, "weka/classifiers/trees/J48")
kdd_j48 = scalabilityTest(kddcup, "weka/classifiers/trees/J48")
pok_j48 = scalabilityTest(poker, "weka/classifiers/trees/J48")
pro_j48 = scalabilityTest(protein, "weka/classifiers/trees/J48")
cov_rf = scalabilityTest(covertype, "weka/classifiers/trees/RandomForest", Weka_control(I = 50, "num-slots" = 1))
kdd_rf = scalabilityTest(kddcup, "weka/classifiers/trees/RandomForest", Weka_control(I = 50, "num-slots" = 1))
pok_rf = scalabilityTest(poker, "weka/classifiers/trees/RandomForest", Weka_control(I = 50, "num-slots" = 1))
pro_rf = scalabilityTest(protein, "weka/classifiers/trees/RandomForest", Weka_control(I = 50, "num-slots" = 1))
```

```{r stratified_test}
stratifiedTest = function(set, classifier, control = Weka_control()) {
  pred = getPredictions(set, classifier, control, stratified = TRUE)
  
  simpleVote <- function() {}
    
  
}
```

```{r stratified}
scov_j48 = stratifiedTest(covertype, "weka/classifiers/trees/J48")
skdd_j48 = stratifiedTest(kddcup, "weka/classifiers/trees/J48")
spok_j48 = stratifiedTest(poker, "weka/classifiers/trees/J48")
spro_j48 = stratifiedTest(protein, "weka/classifiers/trees/J48")
scov_rf = stratifiedTest(covertype, "weka/classifiers/trees/RandomForest", Weka_control(I = 50, "num-slots" = 1))
skdd_rf = stratifiedTest(kddcup, "weka/classifiers/trees/RandomForest", Weka_control(I = 50, "num-slots" = 1))
spok_rf = stratifiedTest(poker, "weka/classifiers/trees/RandomForest", Weka_control(I = 50, "num-slots" = 1))
spro_rf = stratifiedTest(protein, "weka/classifiers/trees/RandomForest", Weka_control(I = 50, "num-slots" = 1))
```
